export const stonesMockData = [
  {
    id: 'river-black-granite',
    name_ar: 'غرانيت ريفر بلاك',
    nameEn: 'River Black',
    type: 'granite',
    color: 'black',
    thickness: 2,
    size: '290 × 104 سم',
    description:
      'نقدم لكم أحد أجمل وأفخم الألواح المتوفرة لدينا، خامة عالية الجودة ولمسة فاخرة تناسب جميع الأعمال من المطابخ إلى الديكورات الراقية.',
    image: '/images/granite.jpg',
    available: true,
    useCases: ['مطابخ', 'واجهات', 'أرضيات'],
  },
  {
    id: 'star-galaxy-granite',
    name_ar: 'غرانيت ستار جالكسي',
    nameEn: 'Star Galaxy',
    type: 'granite',
    color: 'black',
    thickness: 2,
    size: '320 × 190 سم',
    description:
      'غرانيت فاخر بلون أسود عميق ونقاط ذهبية طبيعية، مثالي للمطابخ والمساحات العصرية.',
    image: '/images/granite.jpg',
    available: true,
    useCases: ['مطابخ', 'كاونترات'],
  },
  {
    id: 'calacatta-oro-marble',
    name_ar: 'رخام كلكتا أورو',
    nameEn: 'Calacatta Oro',
    type: 'marble',
    color: 'white',
    thickness: 2,
    size: '200 × 120 سم',
    description:
      'رخام إيطالي فاخر بخطوط ذهبية أنيقة، يضفي طابعاً راقياً على المساحات الداخلية.',
    image: '/images/marble.jpg',
    available: true,
    useCases: ['أرضيات', 'جدران', 'صالات'],
  },
  {
    id: 'taj-mahal-marble',
    name_ar: 'رخام تاج محل',
    nameEn: 'Taj Mahal',
    type: 'marble',
    color: 'beige',
    thickness: 2,
    size: '320 × 190 سم',
    description:
      'رخام بلون بيج دافئ ونقوش طبيعية ناعمة، مناسب للأرضيات والديكورات الراقية.',
    image: '/images/marble.jpg',
    available: true,
    useCases: ['أرضيات', 'جدران'],
  },
  {
    id: 'daino-beige-marble',
    name_ar: 'رخام داينو بيج',
    nameEn: 'Daino Beige',
    type: 'marble',
    color: 'beige',
    thickness: 2,
    size: '300 × 180 سم',
    description:
      'خيار مثالي للمساحات الهادئة، يتميز بلونه الدافئ وسهولة دمجه مع مختلف التصاميم.',
    image: '/images/marble.jpg',
    available: false,
    useCases: ['أرضيات', 'مداخل'],
  },
  {
    id: 'aliveri-grey-marble',
    name_ar: 'رخام أليفيري رمادي',
    nameEn: 'Aliveri Grey',
    type: 'marble',
    color: 'grey',
    thickness: '3 سم',
    size: '390 × 145 سم',
    description:
      'رخام رمادي أنيق بملمس عصري، مناسب للمشاريع السكنية والتجارية.',
    image: '/images/marble.jpg',
    available: true,
    useCases: ['جدران', 'حمامات', 'أرضيات'],
  },
]
